#!/bin/bash

export POGHOME=./

export CLASSPATH=${POGHOME}:${POGHOME}/classfiles2:${POGHOME}/jars/looks-1.3.1.jar:${POGHOME}/jars/epsgraphics.jar:${POGHOME}/jars/forms-1.1.0.jar:${POGHOME}/jars/pal-cvs.jar:${POGHOME}/jars/colt.jar:${POGHOME}/jars/concurrent.jar

java -jar jars/pogvue.jar -Xmx8096M pogvue.gui.hub.GFFTableModel -lenfile data/strCam.chrlen -bandfile data/strCam.cytoband.txt -gfffile $1
