#!/bin/tcsh

setenv POGHOME ./

setenv CLASSPATH ${POGHOME}:${POGHOME}/classfiles:${POGHOME}/jars/looks-1.3.1.jar:${POGHOME}/jars/epsgraphics.jar:${POGHOME}/jars/forms-1.1.0.jar:${POGHOME}/jars/pal-cvs.jar

head -1 ${POGHOME}/data/gnfAtlas2.gene_info.clus > /tmp/exp
grep $1 ${POGHOME}/data/gnfAtlas2.gene_info.clus |grep -v fetal_brain>> /tmp/exp
java -mx512M pogvue.gui.ExpressionPanel -expfile  /tmp/exp
