#!/bin/tcsh

setenv POGHOME ./

setenv CLASSPATH ${POGHOME}:${POGHOME}/classfiles:${POGHOME}/jars/looks-1.3.1.jar:${POGHOME}/jars/epsgraphics.jar:${POGHOME}/jars/forms-1.1.0.jar:${POGHOME}/jars/pal-cvs.jar

java -mx512M pogvue.gui.hub.TransfacTableModel -matrixfile ${POGHOME}/data/pwms_union.txt -format ormat
