#!/bin/csh

setenv POGHOME .

setenv CLASSPATH ${POGHOME}:${POGHOME}/classfiles:${POGHOME}/jars/looks-1.3.1.ja
r:${POGHOME}/jars/epsgraphics.jar:${POGHOME}/jars/forms-1.1.0.jar:${POGHOME}/jar
s/pal-cvs.jar

/cygdrive/c/Program\ Files/Java/jdk1.6.0_02/bin/javac -d classfiles -cp `cygpat
h -wp $CLASSPATH` pogvue/datamodel/Alignment.java

